AWSTemplateFormatVersion: '2010-09-09'
Description: 'ACM Certificate Stack in us-east-1'

Parameters:
  DomainName:
    Type: String
    Description: "Domain Name (e.g., example.com)"
  
  HostedZoneId:
    Type: String
    Description: "Route 53 Hosted Zone ID"

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub www.${DomainName}
        - !Sub m.${DomainName}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Description: "ARN of the created certificate"
    Value: !Ref Certificate
    Export:
      Name: !Sub "${AWS::StackName}-CertificateArn"
      
