AWSTemplateFormatVersion: '2010-09-09'
Description: 'ACM Certificate in us-east-1 for CloudFront'

Parameters:
  DomainName:
    Type: String
    Description: "Domain Name (e.g., example.com)"
  
  HostedZoneId:
    Type: String
    Description: "Route 53 Hosted Zone ID"

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub www.${DomainName}
        - !Sub m.${DomainName}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Description: ARN of the created certificate
    Value: !Ref Certificate
---

# メインのテンプレート（任意のリージョンで実行）
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Multi-domain Web Infrastructure with existing ALB, CloudFront and ACM (IPv4 only)'

Parameters:
  DomainName:
    Type: String
    Description: "Domain Name (e.g., example.com)"
  
  HostedZoneId:
    Type: String
    Description: "Route 53 Hosted Zone ID"
  
  ExistingALBDNSName:
    Type: String
    Default: "dualstack.lab5-1668943645.ap-northeast-1.elb.amazonaws.com"
    Description: "ALB domain Name"

  CertificateArn:
    Type: String
    Description: "ARN of the certificate in us-east-1"

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref DomainName
          - !Sub www.${DomainName}
          - !Sub m.${DomainName}
        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            Headers:
              - Host
              - Origin
            Cookies:
              Forward: all
        Origins:
          - DomainName: !Ref ExistingALBDNSName
            Id: ALBOrigin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
        PriceClass: PriceClass_200
        HttpVersion: http2
        IPV6Enabled: false

  NakedDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  WWWDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub www.${DomainName}
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  MobileDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub m.${DomainName}
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  CloudFrontDomainName:
    Description: Domain name of CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
    
